apiVersion: v1
data:
  defaultFilePosture: audit
  defaultCapabilitiesPosture: audit
  defaultNetworkPosture: audit
  visibility: none
kind: ConfigMap
metadata:
  labels:
    kubearmor-app: kubearmor-configmap
  name: kubearmor-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kubearmorController.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 5c4b1500.kubearmor.com
