apiVersion: v1
data:
  defaultFilePosture: audit
  defaultCapabilitiesPosture: audit
  defaultNetworkPosture: audit
  visibility: process,file,network
kind: ConfigMap
metadata:
  labels:
    kubearmor-app: kubearmor-configmap
  name: kubearmor-config
  namespace: {{ .Release.Namespace }}
