name: ci-test-controllers

on:
  push:
    branches:
      - "main"
    paths:
      - "pkg/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "pkg/**"

jobs:
  kubearmor-controller-build:
    name: Build and Deploy KubeArmorController
    defaults:
      run:
        working-directory: ./pkg/KubeArmorController
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "v1.20"

      - uses: actions/checkout@v3

      - name: Build KubeArmorController
        run: make docker-build TAG=latest
